"use strict";
exports.__esModule = true;
var LinkedList_1 = require("./LinkedList");
var list = new LinkedList_1.LinkedList();
list.append("Aishik");
list.append("John");
list.append("Jack");
list.append("Peter");
list.append("Aishik");
list.append("John");
list.append("Jack");
list.append("Peter");
list.deleteFirst("Jack");
list.display();
console.log("...............................................");
list.deleteLast("John");
list.display();
console.log("...............................................");
list.reverseDisplay();
